<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.6.1" />
    <PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\OnionArch.Application\OnionArch.Application.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\..\infrastructure\OnionArch.Persistance\OnionArch.Persistance.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\..\infrastructure\OnionArch.infrastructure\OnionArch.infrastructure.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\..\SignalR\SignalR.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Controllers\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Logs\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="wwwroot\" />
    <Content Remove="wwwroot\resource\product-images\Araba.png" />
    <Content Remove="wwwroot\resource\product-images\Araba-2.png" />
    <Content Remove="wwwroot\resource\product-images\Araba-3.png" />
    <Content Remove="wwwroot\resource\product-images\AvukatimOl.png" />
    <Content Remove="wwwroot\resource\product-images\Logo.png" />
  </ItemGroup>
</Project>
